# Generated by Django 5.2.8 on 2025-11-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=30)),
                ('user_identifier', models.CharField(max_length=30)),
                ('platform_icon', models.ImageField(blank=True, null=True, upload_to='platform_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='QuickMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('overview', models.CharField(max_length=200)),
                ('refimage', models.ImageField(blank=True, null=True, upload_to='quickmenuimages/')),
            ],
        ),
    ]
